### ISSUE TITLE
分数提交失败，服务器开小差啦？

### ISSUE THREAD

**Issue by JizhiXiang** [Mocha-L/wechat_wegoing#3]
用Packet Capture抓包时出现：“分数提交失败，服务器开小差啦”，然后找不到相应的包怎么办？

**Comment by Allen151** [comment]
手机的证书没安装成功，你看看电脑上的Charles 软件中对应微信游戏的网站是否提示undefined。
安装成功的标志是手机上提示你输入手机解锁密码。

**Comment by JizhiXiang** [comment]
@Allen151 可是我用的是作者第二种抓包方法，直接在手机上安装Packet Capture，没用到Charles，也要安装证书吗？
（我第一种办法卡在了“访问chls.pro/ssl ”这块，可能是局域网没连接成功，ipconfig后不知道选哪个本地ip，试了些也不对）

**Comment by Mocha-L** [comment]
@JizhiXiang 抓包过程出现这个问题可能是你的网络有问题（可能是之前给wifi配置了代理端口，但是代理没运行导致的问题），建议把wifi断开，只用Packet Capture来抓包，应该可以抓到的。
你试试~

**Comment by yehuozhili** [comment]
抓包抓了sessionid 运行code 输入sessionid后提示{'errcode': -1702220400, 'errmsg': ''}
sorry, some error happend! please contact the author.

**Comment by Mocha-L** [comment]
@yehuozhili 这个报错很可能是Sessionid不对 或者已经失效
多半是不对~
你可以把更详细的信息，比如抓包截图和运行截图放上来。

**Comment by yehuozhili** [comment]
成功了 是session里面多复制了末尾的http/1.1

**Comment by Mocha-L** [comment]
@yehuozhili 恭喜~
